### ISSUE TITLE
[Bug] otp.add failed

### ISSUE THREAD

**Issue by dasoops** [koishijs/koishi-plugin-otp#9]
```log
2024-08-19 16:23:10 [D] command otp.add github ******
2024-08-19 16:23:10 [D] sqlite > SELECT `id`, `bid`, `name`, `token`, `method`, `threshold`, `algorithm`, `digits`, `counter`, `period`, `initial`, `created_at`, `updated_at` FROM `otp` cbutlnup WHERE `bid` = 2 AND `name` = 'github' []
2024-08-19 16:23:10 [W] command otp.add github ******
                        Error: missing primary key
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at Array.<anonymous> (C:\dasoops\workSpace\js\koishi-app\node_modules\@koishijs\core\src\command\command.ts:291:14)
                            at _Command.execute (C:\dasoops\workSpace\js\koishi-app\node_modules\@koishijs\core\src\command\command.ts:307:22)
                            at <anonymous> (C:\dasoops\workSpace\js\koishi-app\node_modules\@koishijs\core\src\session.ts:443:22)
                            at Proxy.withScope (C:\dasoops\workSpace\js\koishi-app\node_modules\@koishijs\core\src\session.ts:342:22)
                            at next (C:\dasoops\workSpace\js\koishi-app\node_modules\@koishijs\core\src\middleware.ts:258:16)
                            at next (C:\dasoops\workSpace\js\koishi-app\node_modules\@koishijs\core\src\middleware.ts:258:16)
                            at Processor._handleMessage (C:\dasoops\workSpace\js\koishi-app\node_modules\@koishijs\core\src\middleware.ts:269:22)
```

https://github.com/cordiverse/minato/blob/c239d6c68b884ad08e41f06c38aecf8886cd1cc7/packages/core/src/database.ts#L508-L513

may need `autoInc`?

**Comment by Lipraty** [comment]
fixed.
but currently outdated, we needs update the dependencies before it can be released.
